services:
  - type: web
    name: siet-esports-hub
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npx ts-node prisma/seed.ts && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://siet-esports-hub.vercel.app
